// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFjeD1XmnQahkOHIxmrvaU__58tiUG3xU',
    appId: '1:695695824497:web:2a7d57073ee5c9ec9aadd0',
    messagingSenderId: '695695824497',
    projectId: 'e-learn-ea824',
    authDomain: 'e-learn-ea824.firebaseapp.com',
    storageBucket: 'e-learn-ea824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFjeD1XmnQahkOHIxmrvaU__58tiUG3xU',
    appId: '1:695695824497:android:2a7d57073ee5c9ec9aadd0',
    messagingSenderId: '695695824497',
    projectId: 'e-learn-ea824',
    storageBucket: 'e-learn-ea824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbwmqZ9zM7maqT23fTxln2LsbJZ4MGuM',
    appId: '1:695695824497:ios:198a588a57fb8ba19aadd0',
    messagingSenderId: '695695824497',
    projectId: 'e-learn-ea824',
    storageBucket: 'e-learn-ea824.firebasestorage.app',
    iosClientId:
        '695695824497-get115ab8eojgeco75kt8bh7kgn42i0v.apps.googleusercontent.com',
    iosBundleId: 'com.hackethos4u.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFjeD1XmnQahkOHIxmrvaU__58tiUG3xU',
    appId: '1:695695824497:web:2a7d57073ee5c9ec9aadd0',
    messagingSenderId: '695695824497',
    projectId: 'e-learn-ea824',
    authDomain: 'e-learn-ea824.firebaseapp.com',
    storageBucket: 'e-learn-ea824.firebasestorage.app',
  );
}
